"""Curriculum for the Learn page.

Each lesson has steps. A step names the binding it teaches by Omarchy's own description ("k"), which
build_portal.py resolves to your current keys, and a "check" the page verifies live through the local
helper (/api/state) — so the lesson knows you actually did it. Check types (see learn.template.html):
  newWindow{cls}  closeWindow  wsIs{ws}  wsChange  moved  floating{v}  fullscreen{v}  special{v}
  toSpecial  focusChange  grouped  themeChanged  volumeChanged  newShot  typed{re}  manual
"""

import kitconf

DRAG = kitconf.three_fingers() == "drag"  # three fingers drag instead of swiping spaces (trackpad/three-fingers)
FN = "4" if DRAG else "3"  # fingers for the space swipe the lessons teach


def S(en, es, k=None, check="manual", menu=None, **kw):
    d = {"en": en, "es": es, "check": check}
    if k: d["k"] = k
    if menu: d["menu"] = menu
    d.update(kw)
    return d


TERM = "terminal|foot|alacritty|ghostty|kitty"
KIT = "~/labspace/omarchy-kit"

LEVELS = [
 {"id": "l1", "en": "1 · Survival: your first hour", "es": "1 · Supervivencia: tu primera hora", "lessons": [
  {"id": "super", "en": "The Super key is your ⌘", "es": "La tecla Super es tu ⌘",
   "why": {"en": "On your MacBook, the ⌘ command key acts as Omarchy's Super key. Almost every shortcut starts with it, much as most macOS shortcuts start with ⌘.",
           "es": "En tu MacBook, la tecla ⌘ (comando) funciona como la tecla Super de Omarchy. Casi todos los atajos empiezan con ella, igual que la mayoría en macOS empiezan con ⌘."},
   "steps": [S("Open the list of every shortcut. Read it, then close it with Esc.", "Abre la lista de todos los atajos. Léela y ciérrala con Esc.", k="Keybindings"),
             S("Open a terminal. It's your power tool, like Terminal.app.", "Abre una terminal. Es tu herramienta más potente, como Terminal.app.", k="Terminal", check="newWindow", cls="terminal|foot|alacritty|ghostty|kitty")]},
 {"id": "firstcmd", "en": "Your first command", "es": "Tu primer comando",
   "why": {"en": "A terminal takes written instructions called commands: you type one, press Enter, and it answers. Nothing here changes your system, and a command that fails just prints an error and stops, so you cannot break anything by trying. Later lessons show commands in grey boxes: click one to copy it, paste it into the terminal with Super+V, press Enter.",
           "es": "Una terminal recibe instrucciones escritas llamadas comandos: escribes uno, pulsas Enter y responde. Nada de esto cambia tu sistema, y un comando que falla solo muestra un error y se detiene, así que no puedes romper nada por probar. Las lecciones siguientes muestran comandos en cajas grises: haz clic en uno para copiarlo, pégalo en la terminal con Super+V y pulsa Enter."},
   "steps": [S("Open a terminal.", "Abre una terminal.", k="Terminal", check="newWindow", cls="terminal|foot|alacritty|ghostty|kitty"),
             S("Type  echo hello  in the terminal and press Enter. echo repeats what you give it. Type the word it printed in the box below.",
               "Escribe  echo hello  en la terminal y pulsa Enter. echo repite lo que le des. Escribe en el recuadro de abajo la palabra que mostró.",
               check="typed", re="^\\s*hello\\s*$", box=True),
             S("Now paste instead of typing: click the command to copy it, press Super+V in the terminal, then Enter. It prints the year; type it below.",
               "Ahora pega en vez de escribir: haz clic en el comando para copiarlo, pulsa Super+V en la terminal y luego Enter. Muestra el año; escríbelo abajo.",
               k="Universal paste", cmd="date +%Y", check="typed", re="^\\s*20\\d\\d\\s*$", box=True),
             S("Make a mistake on purpose: type  hello-world  and press Enter. The error (command not found) is normal and harmless; it just means no program has that name.",
               "Equivócate a propósito: escribe  hello-world  y pulsa Enter. El error (command not found) es normal e inofensivo: solo significa que ningún programa se llama así."),
             S("Stop a command that is running: type  sleep 100  and press Enter (the terminal waits), then press Ctrl+C to interrupt it. Ctrl+C is the way out of almost anything.",
               "Detén un comando en marcha: escribe  sleep 100  y pulsa Enter (la terminal espera), luego pulsa Ctrl+C para interrumpirlo. Ctrl+C es la salida de casi todo.")]},
  {"id": "close", "en": "Closing windows", "es": "Cerrar ventanas",
   "why": {"en": "There are no red/yellow/green buttons. Windows close from the keyboard; for most apps, closing the last window also quits the app.",
           "es": "No hay botones rojo/amarillo/verde. Las ventanas se cierran con el teclado; en la mayoría de apps, cerrar la última ventana también cierra la app."},
   "steps": [S("Close the terminal you opened.", "Cierra la terminal que abriste.", k="Close window", check="closeWindow")]},
  {"id": "launch", "en": "Launching apps (your Spotlight)", "es": "Abrir apps (tu Spotlight)",
   "why": {"en": "The apps menu works like Spotlight: open it, type a few letters, press Return. The Omarchy menu is the hub for everything else: installing, style, settings, system.",
           "es": "El menú de apps funciona como Spotlight: ábrelo, escribe unas letras y pulsa Return. El menú de Omarchy es el centro para todo lo demás: instalar, estilo, ajustes, sistema."},
   "steps": [S("Open the apps menu, type “nautilus” (the file manager) and press Return.", "Abre el menú de apps, escribe “nautilus” (el gestor de archivos) y pulsa Return.", k="Apps menu", check="newWindow"),
             S("Open the Omarchy menu and look around. Esc closes it.", "Abre el menú de Omarchy y explóralo. Esc lo cierra.", k="Omarchy menu", menu="root")]},
  {"id": "spaces", "en": "Spaces (workspaces)", "es": "Espacios (workspaces)",
   "why": {"en": "Spaces 1–9 are separate desktops, like Mission Control's Spaces but always there and numbered. Keep a habit: browser on 2, chat on 8, and so on.",
           "es": "Los espacios 1–9 son escritorios separados, como los Spaces de Mission Control pero siempre presentes y numerados. Crea un hábito: navegador en 2, chat en 8, etc."},
   "steps": [S("Jump to space 2.", "Salta al espacio 2.", k="Switch to workspace 2", check="wsIs", ws=2),
             S("Come back to space 1.", "Vuelve al espacio 1.", k="Switch to workspace 1", check="wsIs", ws=1),
             S(f"Now do it with your fingers: swipe left or right with {FN} fingers on the trackpad.", f"Ahora con los dedos: desliza a la izquierda o derecha con {FN} dedos en el trackpad.", check="wsChange", gesture=f"{FN} ↔")]},
  {"id": "move", "en": "Moving a window to another space", "es": "Mover una ventana a otro espacio",
   "why": {"en": "Rather than dragging windows between desktops, you send the focused window to a numbered space.",
           "es": "En lugar de arrastrar ventanas entre escritorios, envías la ventana enfocada a un espacio numerado."},
   "steps": [S("Open any window (a terminal is fine).", "Abre cualquier ventana (una terminal sirve).", k="Terminal", check="newWindow"),
             S("Send it to space 3. You follow it there.", "Envíala al espacio 3. Tú la sigues.", k="Move window to workspace 3", check="moved")]},
  {"id": "system", "en": "Lock, sleep, shut down", "es": "Bloquear, suspender, apagar",
   "why": {"en": "The System menu replaces the Apple menu's Sleep, Restart, Shut Down and Log Out. Closing the lid also locks and suspends (light sleep); Hibernate, for a long break, saves your session to disk and powers off.",
           "es": "El menú Sistema reemplaza Suspender, Reiniciar, Apagar y Cerrar sesión del menú Apple. Cerrar la tapa también bloquea y suspende (reposo ligero); Hibernar, para una pausa larga, guarda tu sesión en el disco y se apaga."},
   "steps": [S("Open the System menu, look at the options, then press Esc.", "Abre el menú Sistema, mira las opciones y pulsa Esc.", k="System menu", menu="system"),
             S("Learn the lock shortcut (try it when you're ready; your password unlocks).", "Aprende el atajo de bloqueo (pruébalo cuando quieras; tu contraseña desbloquea).", k="Lock system")]},
 ]},
 {"id": "l2", "en": "2 · Windows like a pro", "es": "2 · Ventanas como profesional", "lessons": [
  {"id": "focus", "en": "Moving focus without the mouse", "es": "Mover el foco sin el ratón",
   "why": {"en": "Windows tile side by side automatically. Move between them with Super and the arrow keys.",
           "es": "Las ventanas se acomodan solas lado a lado. Muévete entre ellas con Super y las flechas."},
   "steps": [S("Make sure two windows share this space (open a second terminal if needed).", "Asegúrate de tener dos ventanas en este espacio (abre otra terminal si hace falta).", k="Terminal", check="newWindow"),
             S("Move focus to the window on the left.", "Mueve el foco a la ventana de la izquierda.", k="Focus on left window", check="focusChange")]},
  {"id": "float", "en": "Floating windows (the macOS way)", "es": "Ventanas flotantes (al estilo macOS)",
   "why": {"en": "Any window can float freely like on a Mac. Drag it with Super and the left mouse button; resize it with Super and the right button.",
           "es": "Cualquier ventana puede flotar libremente como en Mac. Arrástrala con Super + clic izquierdo; cambia su tamaño con Super + clic derecho."},
   "steps": [S("Make the focused window float.", "Haz flotar la ventana enfocada.", k="Toggle window floating/tiling", check="floating", v=True),
             S("Put it back into the tiling layout.", "Devuélvela al mosaico.", k="Toggle window floating/tiling", check="floating", v=False)]},
  {"id": "fullscreen", "en": "Full screen", "es": "Pantalla completa",
   "why": {"en": "Like ⌃⌘F on macOS, but on a tiling desktop it's instant and stays on the same space.", "es": "Como ⌃⌘F en macOS, pero en un escritorio de mosaico es instantáneo y se queda en el mismo espacio."},
   "steps": [S("Make the focused window full screen.", "Pon la ventana enfocada en pantalla completa.", k="Full screen", check="fullscreen", v=True),
             S("Exit full screen.", "Sal de pantalla completa.", k="Full screen", check="fullscreen", v=False)]},
  {"id": "resize", "en": "Resizing and splitting", "es": "Redimensionar y dividir",
   "why": {"en": "Tiles grow and shrink from the keyboard. Super+J flips how the space is split (side by side or stacked).",
           "es": "Los mosaicos crecen y encogen con el teclado. Super+J cambia la división (lado a lado o apilado)."},
   "steps": [S("Grow the focused window.", "Agranda la ventana enfocada.", k="Expand window left"),
             S("Shrink it back.", "Encógela de nuevo.", k="Shrink window left"),
             S("Flip the split direction.", "Cambia la dirección de la división.", k="Toggle window split")]},
  {"id": "scratchpad", "en": "The scratchpad (instead of minimize)", "es": "El scratchpad (en vez de minimizar)",
   "why": {"en": "There's no minimize (⌘M) on a tiling desktop. Instead you park a window in the hidden scratchpad and summon it back over anything.",
           "es": "No existe minimizar (⌘M) en un escritorio de mosaico. En su lugar estacionas una ventana en el scratchpad oculto y la invocas sobre cualquier cosa."},
   "steps": [S("Send the focused window to the scratchpad.", "Envía la ventana enfocada al scratchpad.", k="Move window to scratchpad", check="toSpecial"),
             S("Show the scratchpad.", "Muestra el scratchpad.", k="Toggle scratchpad", check="special", v=True),
             S("Hide it again.", "Ocúltalo otra vez.", k="Toggle scratchpad", check="special", v=False)]},
  {"id": "groups", "en": "Tabbed groups", "es": "Grupos con pestañas",
   "why": {"en": "Several windows can share one tile as tabs, which suits small screens.", "es": "Varias ventanas pueden compartir un mosaico como pestañas; ideal para pantallas pequeñas."},
   "steps": [S("Turn the focused window into a group.", "Convierte la ventana enfocada en un grupo.", k="Toggle window grouping"),
             S("Move a neighbour into the group (Super+Alt+arrow), then switch tabs.", "Mueve una vecina al grupo (Super+Alt+flecha) y cambia de pestaña.", k="Next window in group", check="grouped")]},
 ]},
 {"id": "l3", "en": "3 · Everyday tasks", "es": "3 · Tareas diarias", "lessons": [
  {"id": "accents", "en": "Typing Spanish: á é í ó ú ñ ¿ ¡", "es": "Escribir en español: á é í ó ú ñ ¿ ¡",
   "why": {"en": "Accents work like on your Mac, on the RIGHT Option key (⌥): press ⌥ and e together, release, then type the vowel: ⌥e then a gives á. ⌥n then n gives ñ, ⌥u then u gives ü, ⌥1 gives ¡, and ⌥ Shift / gives ¿. The left Option key stays Alt. A second way: Caps Lock is a Compose key (press it, release, then ' and a gives á). For real Caps Lock, press both Shift keys.",
           "es": "Los acentos funcionan como en tu Mac, con la tecla Option (⌥) DERECHA: pulsa ⌥ y e juntas, suelta y escribe la vocal: ⌥e y luego a da á. ⌥n y luego n da ñ, ⌥u y luego u da ü, ⌥1 da ¡ y ⌥ Shift / da ¿. La tecla Option izquierda sigue siendo Alt. Una segunda forma: Bloq Mayús es una tecla Compose (púlsala, suéltala y escribe ' y a da á). Para el Bloq Mayús real pulsa ambos Shift."},
   "steps": [S("In the box below, type: ¿Año? ¡Sí!   (right ⌥ Shift / for ¿, right ⌥ n then n for ñ, right ⌥ 1 for ¡, right ⌥ e then i for í)", "En el recuadro de abajo escribe: ¿Año? ¡Sí!   (⌥ derecho Shift / para ¿, ⌥ derecho n y luego n para ñ, ⌥ derecho 1 para ¡, ⌥ derecho e y luego i para í)", check="typed", re="¿.*ñ.*\\?.*¡.*í", box=True)]},
  {"id": "copy", "en": "Copy, paste and clipboard history", "es": "Copiar, pegar e historial del portapapeles",
   "why": {"en": "Super+C and Super+V copy and paste everywhere, terminals included, so your ⌘C/⌘V muscle memory keeps working. The clipboard manager remembers what you copied earlier.",
           "es": "Super+C y Super+V copian y pegan en todas partes, incluso en terminales, así que tu memoria de ⌘C/⌘V sigue sirviendo. El gestor de portapapeles recuerda lo que copiaste antes."},
   "steps": [S("Select this word: Omarchy, then copy it with the universal copy.", "Selecciona esta palabra: Omarchy, y cópiala con el copiar universal.", k="Universal copy"),
             S("Open the clipboard history and pick it again.", "Abre el historial del portapapeles y elígela de nuevo.", k="Clipboard manager"),
             S("Paste it into the box below.", "Pégala en el recuadro de abajo.", k="Universal paste", check="typed", re="Omarchy", box=True)]},
  {"id": "cmdkeys", "en": "Your ⌘ shortcuts inside apps", "es": "Tus atajos ⌘ dentro de las apps",
   "why": {"en": "Inside apps, your ⌘ key now sends Ctrl for the common Mac shortcuts: ⌘A select all, ⌘Z undo (⇧⌘Z redo), ⌘R reload, ⌘N new window, ⇧⌘T reopen a closed tab, ⌘D bookmark, ⌘B/⌘I/⌘U bold, italic, underline, ⌘[ and ⌘] back and forward. Terminals are skipped on purpose. ⌘W, ⌘T, ⌘F, ⌘S, ⌘L, ⌘G and ⌘P are opt-in, key by key, because Super+those keys already do Omarchy things (see From macOS).",
           "es": "Dentro de las apps, tu tecla ⌘ ahora envía Ctrl para los atajos comunes de Mac: ⌘A seleccionar todo, ⌘Z deshacer (⇧⌘Z rehacer), ⌘R recargar, ⌘N ventana nueva, ⇧⌘T reabrir pestaña cerrada, ⌘D marcador, ⌘B/⌘I/⌘U negrita, cursiva y subrayado, ⌘[ y ⌘] atrás y adelante. Las terminales se omiten a propósito. ⌘W, ⌘T, ⌘F, ⌘S, ⌘L, ⌘G y ⌘P son opcionales, tecla por tecla, porque Super+esas teclas ya hacen cosas de Omarchy (ver Desde macOS)."},
   "steps": [S("In the box below, type: casa. Then press Select all, and type: hogar. The box should end up holding only “hogar”.", "En el recuadro de abajo escribe: casa. Luego pulsa Seleccionar todo y escribe: hogar. El recuadro debe quedar solo con “hogar”.", k="Select all (⌘A)", check="typed", re="^hogar$", box=True),
             S("Press Undo in the box: the previous text comes back.", "Pulsa Deshacer en el recuadro: vuelve el texto anterior.", k="Undo (⌘Z)"),
             S("Press Reload: this page refreshes, like ⌘R in Safari. Then come back to the Learn page.", "Pulsa Recargar: esta página se actualiza, como ⌘R en Safari. Luego vuelve a la página Aprender.", k="Reload (⌘R)")]},
  {"id": "shots", "en": "Screenshots and screen recording", "es": "Capturas y grabación de pantalla",
   "why": {"en": "Your MacBook has no Print key, so you have a custom shortcut for screenshots, and the Capture menu has everything else: region, window, recording, text recognition (OCR), QR codes, color picker.",
           "es": "Tu MacBook no tiene tecla Print, así que tienes un atajo propio para capturas, y el menú Captura tiene todo lo demás: región, ventana, grabación, reconocimiento de texto (OCR), códigos QR, selector de color."},
   "steps": [S("Take a screenshot: drag over an area, then press Return to save it.", "Toma una captura: arrastra sobre un área y pulsa Return para guardarla.", k="Screenshot", check="newShot"),
             S("Open the Capture menu to see the other tools.", "Abre el menú Captura para ver las otras herramientas.", k="Capture menu", menu="trigger.capture")]},
  {"id": "emoji", "en": "Emoji 😀", "es": "Emoji 😀", "why": {"en": "Like ⌃⌘Space on macOS.", "es": "Como ⌃⌘Espacio en macOS."},
   "steps": [S("Click in the box below, open the emoji picker and choose one.", "Haz clic en el recuadro, abre el selector de emoji y elige uno.", k="Emojis", check="typed", re="\\p{Extended_Pictographic}", box=True)]},
  {"id": "notifs", "en": "Notifications and focus", "es": "Notificaciones y concentración",
   "why": {"en": "Dismiss notifications from the keyboard, see what you missed, and silence everything (Do Not Disturb).", "es": "Descarta notificaciones con el teclado, revisa lo que te perdiste y silencia todo (No molestar)."},
   "steps": [S("Dismiss the last notification.", "Descarta la última notificación.", k="Dismiss last notification"),
             S("Open the notification history.", "Abre el historial de notificaciones.", k="Open notification history"),
             S("Toggle Do Not Disturb (twice to turn it back on).", "Activa No molestar (dos veces para volver).", k="Toggle silencing notifications")]},
  {"id": "nightlight", "en": "Night light and the Activity monitor", "es": "Luz nocturna y monitor de actividad",
   "why": {"en": "Night light is Night Shift. Activity is the Activity Monitor: see what's using CPU and memory, and kill a frozen app.", "es": "La luz nocturna es Night Shift. Actividad es el Monitor de Actividad: ve qué usa CPU y memoria, y cierra una app congelada."},
   "steps": [S("Toggle night light (and back).", "Activa la luz nocturna (y desactívala).", k="Toggle nightlight"),
             S("Open the Activity monitor; press q to quit it.", "Abre el monitor de actividad; pulsa q para salir.", k="Activity", check="newWindow")]},
 ]},
 {"id": "l4", "en": "4 · Make it yours", "es": "4 · Hazlo tuyo", "lessons": [
  {"id": "theme", "en": "Themes", "es": "Temas",
   "why": {"en": "One click restyles the whole desktop: colors, terminal, bar, wallpaper and lock screen. There are 22 built in, and this kit adds six more of its own (install them with themes/install-themes).", "es": "Un clic cambia el estilo de todo el escritorio: colores, terminal, barra, fondo y pantalla de bloqueo. Hay 22 incluidos, y este kit añade seis propios (instálalos con themes/install-themes)."},
   "steps": [S("Open the theme menu and pick a different theme.", "Abre el menú de temas y elige otro tema.", k="Theme menu", check="themeChanged", menu="style.theme"),
             S("Change the background.", "Cambia el fondo.", k="Background switcher", menu="style.background"),
             S("Hide and show the top bar.", "Oculta y muestra la barra superior.", k="Toggle top bar")]},
  {"id": "rebind", "en": "Your own shortcuts", "es": "Tus propios atajos",
   "why": {"en": "Your shortcuts live in ~/.config/hypr/bindings.lua, which Omarchy never overwrites. Add a line, save, and it applies at once.",
           "es": "Tus atajos viven en ~/.config/hypr/bindings.lua, que Omarchy nunca sobrescribe. Añade una línea, guarda y se aplica al instante."},
   "steps": [S("Open the keybindings settings from the Omarchy menu.", "Abre los ajustes de atajos desde el menú de Omarchy.", menu="setup.keybindings"),
             S("Example line: o.bind(\"SUPER + SHIFT + R\", \"SSH\", \"alacritty -e ssh my-server\")", "Línea de ejemplo: o.bind(\"SUPER + SHIFT + R\", \"SSH\", \"alacritty -e ssh mi-servidor\")", cmd="hyprctl reload && hyprctl configerrors")]},
  {"id": "install", "en": "Installing software", "es": "Instalar software",
   "why": {"en": "Install menu = App Store. pacman/yay = Homebrew. Web apps turn any site into an app. This portal's Apps tab installs your list with one click.",
           "es": "Menú Instalar = App Store. pacman/yay = Homebrew. Las web apps convierten cualquier sitio en app. La pestaña Apps de este portal instala tu lista con un clic."},
   "steps": [S("Open the Install menu and browse it.", "Abre el menú Instalar y explóralo.", menu="install"),
             S("Turn a website into an app with the Web App installer.", "Convierte un sitio web en app con el instalador de Web Apps.", menu="install.webapp")]},
 ]},
 {"id": "l5", "en": "5 · Your MacBook, mastered", "es": "5 · Tu MacBook, dominada", "lessons": [
  {"id": "fnrow", "en": "The top row (F-keys)", "es": "La fila superior (teclas F)",
   "why": {"en": "Your top row works like on macOS: brightness, keyboard light, media and volume without Fn. Hold Fn for F1–F12 (for example Fn+F9 is Omarchy dictation).",
           "es": "Tu fila superior funciona como en macOS: brillo, luz del teclado, multimedia y volumen sin Fn. Mantén Fn para F1–F12 (por ejemplo Fn+F9 es el dictado de Omarchy)."},
   "steps": [S("Press F12 (volume up) or F11 (volume down).", "Pulsa F12 (subir volumen) o F11 (bajar volumen).", check="volumeChanged", keys="F11 / F12"),
             S("Press F5 and F6 to dim and brighten the keyboard backlight.", "Pulsa F5 y F6 para bajar y subir la luz del teclado.", keys="F5 / F6")]},
  {"id": "gestures", "en": "Trackpad gestures", "es": "Gestos del trackpad",
   "why": {"en": ("4 fingers sideways switch spaces; " if DRAG else "3 or 4 fingers sideways switch spaces; ") + "4 up opens the Omarchy menu; 4 down shows the scratchpad; a 4-finger pinch opens the apps menu. " + ("Three fingers drag: slide them to select text or drag things, with no click. " if DRAG else "") + "Two fingers scroll naturally and two-finger click is right-click.",
           "es": ("4 dedos de lado cambian de espacio; " if DRAG else "3 o 4 dedos de lado cambian de espacio; ") + "4 hacia arriba abre el menú de Omarchy; 4 hacia abajo muestra el scratchpad; pellizcar con 4 dedos abre el menú de apps. " + ("Tres dedos arrastran: deslízalos para seleccionar texto o arrastrar cosas, sin hacer clic. " if DRAG else "") + "Dos dedos desplazan de forma natural y el clic con dos dedos es clic derecho."},
   "steps": [S(f"Swipe with {FN} fingers to change space.", f"Desliza con {FN} dedos para cambiar de espacio.", check="wsChange", gesture=f"{FN} ↔")]
             + ([S("Select text on this page by sliding three fingers across it, with no click.", "Selecciona texto de esta página deslizando tres dedos sobre él, sin hacer clic.", gesture="3 drag")] if DRAG else [])
             + [S("Swipe up with 4 fingers to open the Omarchy menu (Esc closes it).", "Desliza hacia arriba con 4 dedos para abrir el menú de Omarchy (Esc lo cierra).", gesture="4 ↑"),
                S("Swipe down with 4 fingers to show the scratchpad.", "Desliza hacia abajo con 4 dedos para mostrar el scratchpad.", check="special", v=True, gesture="4 ↓")]},
  {"id": "health", "en": "Updates, snapshots and help", "es": "Actualizaciones, instantáneas y ayuda",
   "why": {"en": "Update weekly from the Update menu. Before big changes, take a snapshot, a restore point like Time Machine for the system. Super+K lists every shortcut, and this portal is one shortcut away.",
           "es": "Actualiza cada semana desde el menú Actualizar. Antes de cambios grandes toma una instantánea, un punto de restauración como Time Machine para el sistema. Super+K muestra todos los atajos y este portal está a un atajo."},
   "steps": [S("Open the Update menu (you don't have to run it now).", "Abre el menú Actualizar (no hace falta ejecutarlo ahora).", menu="update"),
             S("Open this portal from anywhere.", "Abre este portal desde cualquier lugar.", k="Omarchy Kit")]},
 ]},
 {"id": "l6", "en": "6 · Care and feeding of your MacBook", "es": "6 · Cuidados de tu MacBook", "lessons": [

 # ------------------------------------------------------------------------------------------------ 1. the lid
 {"id": "lid", "en": "Closing the lid: light sleep and deep sleep", "es": "Cerrar la tapa: reposo ligero y reposo profundo",
  "why": {"en": "On a Mac, closing the lid just works. Here there are two kinds of sleep. Light sleep (s2idle) keeps the machine running at a whisper, so opening the lid wakes it in about a second; the price is a little more battery while it is closed. Deep sleep (S3) switches almost everything off, but on THIS MacBook the lid never wakes it: only a key or the power button does, because that decision lives in Apple's firmware and Linux cannot change it. The kit already set light sleep for you. Closing the lid also locks the screen first.",
          "es": "En un Mac, cerrar la tapa simplemente funciona. Aquí hay dos tipos de reposo. El reposo ligero (s2idle) deja la máquina funcionando en silencio, así que al abrir la tapa despierta en cerca de un segundo; el precio es un poco más de batería con la tapa cerrada. El reposo profundo (S3) apaga casi todo, pero en ESTA MacBook la tapa nunca lo despierta: solo una tecla o el botón de encendido, porque esa decisión vive en el firmware de Apple y Linux no puede cambiarla. El kit ya dejó el reposo ligero. Al cerrar la tapa, la pantalla se bloquea primero."},
  "steps": [
   S("Open a terminal.", "Abre una terminal.", k="Terminal", check="newWindow", cls=TERM),
   S("Ask the kernel which sleep mode is in use: the word in [brackets] is the active one. Type that word below.",
     "Pregunta al kernel qué modo de reposo se usa: la palabra entre [corchetes] es la activa. Escríbela abajo.",
     cmd="cat /sys/power/mem_sleep", check="typed", re="^\\s*\\[?s2idle\\]?\\s*$", box=True),
   S("Sleep the Mac from the System menu (Suspend), wait ten seconds, then wake it by opening the lid or pressing a key. If the screen stays black, press any key, then the power button once: that is the signature of deep sleep, and the previous step should have said s2idle.",
     "Pon la Mac en reposo desde el menú Sistema (Suspender), espera diez segundos y despiértala abriendo la tapa o con una tecla. Si la pantalla sigue negra, pulsa cualquier tecla y luego el botón de encendido una vez: esa es la señal del reposo profundo, y el paso anterior debía decir s2idle.",
     menu="system.suspend"),
   S("Read what really happened: find your sleep in the report and look at its mode (s2idle or deep) and how long it lasted.",
     "Lee qué pasó de verdad: busca tu reposo en el informe y mira su modo (s2idle o deep) y cuánto duró.",
     cmd=KIT + "/sleep/sleep-check"),
  ]},

 # ------------------------------------------------------------------------------------------------ 2. hibernate
 {"id": "hibernate", "en": "Hibernate: powered off, session saved", "es": "Hibernar: apagada, con tu sesión guardada",
  "why": {"en": "Hibernate is the sleep that costs no battery at all: the Mac writes everything in memory to the encrypted disk and powers off completely. On the next start it asks for the disk password and your windows come back as they were. Two details were hard-won here. First, the firmware's own hibernate mode made the Mac switch itself back on a few seconds later, so the kit sets HibernateMode=shutdown (save, then a plain power-off). Second, you would normally type two passwords (disk, then lock screen). The kit skips the lock screen before a plain hibernate only, because the disk password already proves it is you, so you type one. Closing the lid still locks. Saving takes about 30 seconds, during which the screen is unlocked.",
          "es": "Hibernar es el reposo que no gasta nada de batería: la Mac escribe todo lo que hay en memoria en el disco cifrado y se apaga por completo. Al arrancar de nuevo pide la contraseña del disco y tus ventanas vuelven como estaban. Aquí costaron dos detalles. Primero, el modo de hibernación propio del firmware hacía que la Mac se volviera a encender sola a los pocos segundos; por eso el kit fija HibernateMode=shutdown (guardar y apagar sin más). Segundo, normalmente escribirías dos contraseñas (la del disco y la de la pantalla de bloqueo). El kit omite el bloqueo solo antes de una hibernación simple, porque la contraseña del disco ya demuestra que eres tú, así que escribes una. Cerrar la tapa sigue bloqueando. Guardar tarda unos 30 segundos, y durante ese tiempo la pantalla está desbloqueada."},
  "steps": [
   S("Check that this system can hibernate. The command prints the English word yes when it can; type that word below.",
     "Comprueba que este sistema puede hibernar. El comando escribe la palabra inglesa yes si puede; escríbela abajo.",
     cmd="omarchy-hibernation-available && echo yes", check="typed", re="^\\s*yes\\s*$", box=True),
   S("Ask the lock policy what it would do right now. lock is the normal answer; it says hibernate only in the 15 seconds after a plain hibernate begins. Type what it prints.",
     "Pregunta a la política de bloqueo qué haría ahora mismo. lock es la respuesta normal; dice hibernate solo durante los 15 segundos posteriores al inicio de una hibernación simple. Escribe lo que muestra.",
     cmd=KIT + "/sleep/sleep-lock-policy --check", check="typed", re="^\\s*(lock|hibernate)\\s*$", box=True),
   S("Save your work, then hibernate from the System menu and wait until the screen and keyboard light go out (about 30 seconds). Do not press anything while it saves.",
     "Guarda tu trabajo y hiberna desde el menú Sistema; espera a que se apaguen la pantalla y la luz del teclado (unos 30 segundos). No pulses nada mientras guarda.",
     menu="system.hibernate"),
   S("Press the power button, type the disk password when asked (it is the only one) and check that your windows are back. Do not type your password again after the restore: nothing is asking for it and it would land in whatever window has focus.",
     "Pulsa el botón de encendido, escribe la contraseña del disco cuando la pida (es la única) y comprueba que tus ventanas volvieron. No escribas tu contraseña otra vez tras la restauración: nadie la pide y caería en la ventana que tenga el foco."),
   S("Confirm it in the report: it lists 'hibernated and resumed after N min'. If the Mac ever switches itself back on after powering off, the fix is sleep/install-hibernate-mode (it needs sudo, and --remove undoes it); a Mac that never reaches this line did not hibernate.",
     "Confírmalo en el informe: aparece 'hibernated and resumed after N min'. Si la Mac se vuelve a encender sola tras apagarse, la solución es sleep/install-hibernate-mode (pide sudo y --remove la deshace); si nunca aparece esa línea, la Mac no hibernó.",
     cmd=KIT + "/sleep/sleep-check"),
  ]},

 # ------------------------------------------------------------------------------------------------ 3. watts
 {"id": "watts", "en": "Reading your battery in real watts", "es": "Leer tu batería en watts reales",
  "why": {"en": "The percentage says how much is left, not how fast it is going. Watts say the speed, and Wh divided by W gives hours. Your battery holds about 71 Wh when full (roughly 75 % of new, normal for 2014), and a quiet MacBook at normal brightness draws about 20 W on battery: 71 ÷ 20 tells you roughly how long a charge lasts (you will do the sum in step 3). Always read it unplugged: the charger hides the real draw.",
          "es": "El porcentaje dice cuánto queda, no qué tan rápido se va. Los watts dicen la velocidad, y Wh entre W da horas. Tu batería guarda unos 71 Wh llena (cerca del 75 % de la original, normal en 2014), y una MacBook en calma con brillo normal gasta unos 20 W con batería: 71 ÷ 20 te dice más o menos cuánto dura una carga (harás la cuenta en el paso 3). Léelo siempre sin cargador: el cargador esconde el consumo real."},
  "steps": [
   S("Read the battery from a terminal. Plugged in, the W figure is the charging power, not your use.",
     "Lee la batería desde una terminal. Con el cargador puesto, la cifra en W es la potencia de carga, no tu consumo.",
     cmd="omarchy-battery-status"),
   S("Unplug the charger, leave the Mac alone for a minute, then run this: energy-rate is what the Mac really draws, in watts, and energy-full is what a full charge holds, in Wh.",
     "Desenchufa el cargador, deja la Mac tranquila un minuto y ejecuta esto: energy-rate es lo que la Mac gasta de verdad, en watts, y energy-full es lo que guarda una carga completa, en Wh.",
     cmd="upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E 'energy-full:|energy-rate|percentage|state'"),
   S("Do the sum with your own two numbers: energy-full divided by energy-rate is the hours one charge lasts at that draw. (With 71 Wh and 20 W it comes to about 3.5 hours.)",
     "Haz la cuenta con tus dos números: energy-full entre energy-rate son las horas que dura una carga con ese consumo. (Con 71 Wh y 20 W salen unas 3,5 horas.)"),
   S("See how the kit matches the power profile to the charger (Performance when plugged in, Balanced on battery). Run it, plug or unplug once, run it again.",
     "Mira cómo el kit ajusta el perfil de energía al cargador (Rendimiento con cargador, Equilibrado con batería). Ejecútalo, enchufa o desenchufa una vez y ejecútalo de nuevo.",
     cmd="power-auto --status"),
  ]},

 # ------------------------------------------------------------------------------------------------ 4. levers
 {"id": "levers", "en": "Where the watts go (and the biggest lever)", "es": "A dónde se van los watts (y la palanca más grande)",
  "why": {"en": "Of the roughly 20 W: backlight about 5 W, display electronics about 4.4 W, processor package about 4.8 W, memory about 1.7 W, everything else about 4 W. The biggest lever you control is brightness. A busy terminal adds about 4 W all by itself, because animated text keeps the graphics chip awake, which is why the kit's power tests run from a background service while the terminal sits still. Wi-Fi power saving saves about 0.9 W but is a trade-off, not free: a packet that arrives while the card naps can wait up to one beacon interval, about 100 ms. Invisible for chat and browsing, maybe noticeable in games or calls.",
          "es": "De los casi 20 W: luz de pantalla unos 5 W, electrónica de la pantalla unos 4,4 W, paquete del procesador unos 4,8 W, memoria unos 1,7 W y todo lo demás unos 4 W. La palanca más grande que controlas es el brillo. Una terminal ocupada suma por sí sola unos 4 W, porque el texto animado mantiene despierto al chip gráfico; por eso las pruebas de energía del kit corren desde un servicio en segundo plano mientras la terminal se queda quieta. El ahorro de energía del Wi-Fi ahorra unos 0,9 W pero tiene un costo: un paquete que llega mientras la tarjeta duerme puede esperar hasta un intervalo de baliza, unos 100 ms. No se nota al chatear ni navegar, quizá sí en juegos o llamadas."},
  "steps": [
   S("Unplugged, press F1 several times to dim the screen, wait 30 seconds and read the watts again. F2 brightens; Shift jumps to the minimum or maximum, Alt gives fine steps.",
     "Sin cargador, pulsa F1 varias veces para bajar el brillo, espera 30 segundos y lee otra vez los watts. F2 sube el brillo; Shift salta al mínimo o al máximo y Alt da pasos finos.",
     keys="F1 / F2", cmd="omarchy-battery-status"),
   S("Open Activity (btop) and look at the top of the CPU column: a terminal that is constantly printing is a real power cost. Press q to leave.",
     "Abre Actividad (btop) y mira lo más alto de la columna CPU: una terminal que imprime sin parar tiene un costo real de energía. Pulsa q para salir.",
     k="Activity", check="newWindow"),
   S("Open the lab notebook, find the table 'Where the 20 W goes' and type the backlight's watts. Space moves down a page, q quits.",
     "Abre el cuaderno del laboratorio, busca la tabla 'Where the 20 W goes' y escribe los watts de la luz de pantalla. Espacio baja una página, q sale.",
     cmd="less " + KIT + "/docs/POWER-LAB.md", check="typed", re="^\\s*5([.,]0)?\\s*[Ww]?\\s*$", box=True),
   S("Check Wi-Fi power saving: 'Power save: on' means the card naps between packets. If you ever see Wi-Fi drops or lag, undo it with sudo power/install-wifi-powersave --remove.",
     "Revisa el ahorro de energía del Wi-Fi: 'Power save: on' significa que la tarjeta duerme entre paquetes. Si alguna vez ves cortes o lag en el Wi-Fi, deshazlo con sudo power/install-wifi-powersave --remove.",
     cmd="iw dev $(iw dev | awk '/Interface/{print $2}') get power_save"),
  ]},

 # ------------------------------------------------------------------------------------------------ 5. try themes
 {"id": "themetry", "en": "Themes: how one works, and the kit's six", "es": "Temas: cómo funciona uno y los seis del kit",
  "why": {"en": "An Omarchy theme is a folder, not a setting. Its heart is colors.toml: a short list of named colours (background, foreground, accent, and the eight terminal colours with bright versions). Omarchy's templates turn that palette into the terminal, the bar, btop, Neovim, VS Code and the lock screen; a theme may also carry wallpapers and a preview. The kit ships six of its own in three pairs: Kawaii Bow (light) and Kawaii Bow Night, Mecha Unit and Mecha Unit Red, Solarpunk (light) and Solarpunk Dusk. Switching is instant and nothing is deleted, so try them all.",
          "es": "Un tema de Omarchy es una carpeta, no un ajuste. Su corazón es colors.toml: una lista corta de colores con nombre (fondo, texto, acento y los ocho colores de la terminal con sus versiones brillantes). Las plantillas de Omarchy convierten esa paleta en la terminal, la barra, btop, Neovim, VS Code y la pantalla de bloqueo; un tema también puede traer fondos y una vista previa. El kit trae seis propios en tres parejas: Kawaii Bow (claro) y Kawaii Bow Night, Mecha Unit y Mecha Unit Red, Solarpunk (claro) y Solarpunk Dusk. Cambiar es instantáneo y no se borra nada, así que pruébalos todos."},
  "steps": [
   S("Write down the theme you start from, so you can come back to it.",
     "Anota el tema con el que empiezas, para poder volver a él.",
     cmd="omarchy theme current"),
   S("See which of the kit's themes are installed. If INSTALLED says no, run install-themes with no arguments (no password; it only copies, it switches nothing).",
     "Mira cuáles temas del kit están instalados. Si INSTALLED dice no, ejecuta install-themes sin argumentos (sin contraseña; solo copia, no cambia nada).",
     cmd=KIT + "/themes/install-themes --list"),
   S("Try the light pink one.", "Prueba el rosa claro.",
     cmd='omarchy theme set "Kawaii Bow"', check="themeChanged"),
   S("Now the dark purple command centre. Look at the terminal, the bar and the wallpaper change together.",
     "Ahora el centro de mando morado oscuro. Mira cómo cambian juntos la terminal, la barra y el fondo.",
     cmd='omarchy theme set "Mecha Unit"', check="themeChanged"),
   S("Browse the rest from the Theme menu and pick one: Kawaii Bow Night, Mecha Unit Red, Solarpunk (a truly light one) or Solarpunk Dusk.",
     "Explora el resto desde el menú de temas y elige uno: Kawaii Bow Night, Mecha Unit Red, Solarpunk (uno realmente claro) o Solarpunk Dusk.",
     k="Theme menu", menu="style.theme", check="themeChanged"),
   S("Go back to the theme you wrote down (replace the name).",
     "Vuelve al tema que anotaste (cambia el nombre).",
     cmd='omarchy theme set "<the theme you wrote down>"', check="themeChanged"),
  ]},

 # ------------------------------------------------------------------------------------------------ 6. make a theme
 {"id": "thememake", "en": "Make your own theme", "es": "Crea tu propio tema",
  "why": {"en": "Making a theme is editing a few colours: copy an existing theme folder, give it a name, change a line in colors.toml and apply it. One safety rule: the copies the kit installs carry a hidden .omarchy-kit marker, so install-themes --remove only ever removes its own. If you copy one to start your own theme, delete the marker, or a later --remove would take your theme with it.",
          "es": "Crear un tema es editar unos pocos colores: copia la carpeta de un tema, ponle nombre, cambia una línea de colors.toml y aplícalo. Una regla de seguridad: las copias que instala el kit llevan una marca oculta .omarchy-kit, así que install-themes --remove solo quita lo suyo. Si copias una para empezar tu tema, borra la marca; si no, un --remove posterior se llevaría también tu tema."},
  "steps": [
   S("Look inside a palette: the first lines of Solarpunk's colors.toml. Each line is a name and a colour in #rrggbb form.",
     "Mira dentro de una paleta: las primeras líneas de colors.toml de Solarpunk. Cada línea es un nombre y un color en formato #rrggbb.",
     cmd="head -20 ~/.config/omarchy/themes/solarpunk/colors.toml"),
   S("Start your own theme: copy the folder, then delete the .omarchy-kit marker from the copy.",
     "Empieza tu tema: copia la carpeta y borra la marca .omarchy-kit de la copia.",
     cmd="cp -r ~/.config/omarchy/themes/solarpunk ~/.config/omarchy/themes/my-theme && rm -f ~/.config/omarchy/themes/my-theme/.omarchy-kit"),
   S("Change the accent colour and apply the theme. The folder my-theme appears in the list as My Theme. Any other line in colors.toml works the same way (open it in nvim to edit by hand).",
     "Cambia el color de acento y aplica el tema. La carpeta my-theme aparece en la lista como My Theme. Cualquier otra línea de colors.toml funciona igual (ábrelo en nvim para editar a mano).",
     cmd="sed -i 's/^accent = .*/accent = \"#d6336c\"/' ~/.config/omarchy/themes/my-theme/colors.toml && omarchy theme set \"My Theme\"", check="themeChanged"),
   S("When you are done, switch to another theme first, then remove yours.",
     "Cuando termines, cambia primero a otro tema y luego quita el tuyo.",
     cmd='omarchy theme remove "My Theme"'),
  ]},

 # ------------------------------------------------------------------------------------------------ 7. breaks
 {"id": "breaks", "en": "When something breaks: read the journal", "es": "Cuando algo falla: lee el journal",
  "why": {"en": "Linux keeps a diary: the journal collects every program's messages with a time stamp. When something breaks, do not guess; read what was written at that minute. Most red lines are harmless noise (a Bluetooth speaker that is off, a sound card that is not there); the ones that matter appear exactly when your problem happened. A program that dies leaves a core dump that says how. And the Setup log is the other half: every change made to this Mac, its live status, and the command that undoes it.",
          "es": "Linux lleva un diario: el journal reúne los mensajes de cada programa con su hora. Cuando algo falla, no adivines; lee lo que se escribió en ese minuto. La mayoría de las líneas rojas son ruido inofensivo (una bocina Bluetooth apagada, una tarjeta de sonido que no está); las que importan aparecen justo cuando ocurrió tu problema. Un programa que muere deja un volcado de memoria (core dump) que dice cómo. Y la Bitácora es la otra mitad: cada cambio hecho a esta Mac, su estado en vivo y el comando que lo deshace."},
  "steps": [
   S("Read the errors since this boot (last 20 lines). Do not worry about every line; note which ones match the time of your problem.",
     "Lee los errores desde este arranque (últimas 20 líneas). No te preocupes por cada línea; fíjate en las que coinciden con la hora de tu problema.",
     cmd="journalctl -b -p err --no-pager | tail -20"),
   S("Narrow it to the minute: everything that warned in the last 10 minutes. Change 10 to however long ago the problem happened.",
     "Acótalo al minuto: todo lo que avisó en los últimos 10 minutos. Cambia 10 por hace cuánto ocurrió el problema.",
     cmd='journalctl --since "10 min ago" -p warning --no-pager'),
   S("Ask about one service. This one is the kit's own server. A long 'Traceback' is not automatically a problem: a BrokenPipeError usually just means a browser tab went away while a page was being sent.",
     "Pregunta por un solo servicio. Este es el servidor del propio kit. Un 'Traceback' largo no es necesariamente un problema: un BrokenPipeError suele significar solo que una pestaña del navegador se fue mientras se enviaba una página.",
     cmd="journalctl --user -u omarchy-kit.service -n 20 --no-pager"),
   S("List the programs that crashed, then read the newest. SIGSEGV is a bad memory access, SIGILL is an instruction the CPU does not have, SIGABRT is the program giving up.",
     "Lista los programas que fallaron y lee el más reciente. SIGSEGV es un acceso inválido a memoria, SIGILL es una instrucción que la CPU no tiene y SIGABRT es el programa rindiéndose.",
     cmd="coredumpctl list --no-pager | tail -5 ; coredumpctl info -1 --no-pager | head -25"),
   S("Open the Setup log page (top bar: Setup log, in Spanish Bitácora). Each row has a coloured label: done (green), needs action (amber), pending (grey), manual check (accent colour). Find one that is not green and read its 'how to undo' line.",
     "Abre la página Bitácora (en la barra superior; en inglés, Setup log). Cada fila tiene una etiqueta de color: listo (verde), requiere acción (ámbar), pendiente (gris), revisión manual (color de acento). Busca una que no sea verde y lee su línea de cómo deshacer."),
   S("Asking for help? Put the last five minutes of warnings on the clipboard, then paste them (Super+V) into your message together with what you did and the time.",
     "¿Vas a pedir ayuda? Copia al portapapeles los avisos de los últimos cinco minutos y pégalos (Super+V) en tu mensaje junto con lo que hiciste y la hora.",
     cmd='journalctl --since "5 min ago" -p warning --no-pager | wl-copy'),
  ]},

 # ------------------------------------------------------------------------------------------------ 8. undo
 {"id": "undo", "en": "Undo anything, and read the lab notebook", "es": "Deshaz lo que quieras y lee el cuaderno del laboratorio",
  "why": {"en": "Every change this kit made to the Mac has a way back, and it is always the same: the installer that put it there takes --remove. Three installers need no password (power-auto, hibernate-nolock, themes); four ask for sudo (s2idle, hibernate-mode, battery-log, wifi-powersave). The Setup log lists each change with its undo command, and docs/POWER-LAB.md is the lab notebook: what was measured, what was ruled out, and two things never to do on this machine (rescanning or removing PCI devices, and unloading the thunderbolt driver).",
          "es": "Cada cambio que el kit hizo a la Mac tiene vuelta atrás, y siempre es igual: el instalador que lo puso acepta --remove. Tres instaladores no piden contraseña (power-auto, hibernate-nolock, themes); cuatro piden sudo (s2idle, hibernate-mode, battery-log, wifi-powersave). La Bitácora lista cada cambio con su comando para deshacerlo, y docs/POWER-LAB.md es el cuaderno del laboratorio: qué se midió, qué se descartó y dos cosas que nunca hay que hacer en esta máquina (reescanear o quitar dispositivos PCI, y descargar el controlador thunderbolt)."},
  "steps": [
   S("List every installer the kit has.",
     "Lista todos los instaladores que tiene el kit.",
     cmd="ls ~/labspace/omarchy-kit/{sleep,power,themes}/install-*"),
   S("Find the installers that do NOT ask for sudo (the ones without the 'run it with sudo' line). How many are there? Type the number below.",
     "Busca los instaladores que NO piden sudo (los que no tienen la línea 'run it with sudo'). ¿Cuántos son? Escribe el número abajo.",
     cmd='grep -L "run it with sudo" ~/labspace/omarchy-kit/{sleep,power,themes}/install-*', check="typed", re="^\\s*3\\s*$", box=True),
   S("Practise a safe round trip with a theme you are not using right now: remove it, then install it again. install-themes --list shows the change.",
     "Practica un viaje de ida y vuelta seguro con un tema que no estés usando: quítalo y vuelve a instalarlo. install-themes --list muestra el cambio.",
     cmd=KIT + "/themes/install-themes --remove mecha-unit-red && " + KIT + "/themes/install-themes mecha-unit-red"),
   S("Open the lab notebook and find the table 'What was tried'. The fan floor was lowered from about how many rpm? Type the number.",
     "Abre el cuaderno del laboratorio y busca la tabla 'What was tried'. ¿Desde unas cuántas rpm se bajó la velocidad mínima de los ventiladores? Escribe el número.",
     cmd="less " + KIT + "/docs/POWER-LAB.md", check="typed", re="^\\s*2[,. ]?100\\s*$", box=True),
  ]},
]},
]
