#!/usr/bin/env python3
"""MacBook Pro 15" (2014) speaker voicing: compute the exact response of the biquad chain
and the pre-gain that keeps it at or below -0.5 dB everywhere (no limiter needed).
Unmeasured voicing for small laptop drivers, not a measured correction:
  - 2x high-pass 85 Hz (24 dB/oct): the drivers can't reproduce below ~100 Hz; feeding them
    that energy only causes distortion and steals excursion from the bass they can play.
  - +4 dB at 160 Hz (Q 0.9): warmth near the drivers' useful low end.
  - -2.5 dB at 380 Hz (Q 1.4): chassis "boxiness" typical of laptop enclosures.
  - -1.5 dB at 2.8 kHz (Q 1.2): tame the harsh presence peak small drivers tend to have.
  - +2 dB high shelf at 9 kHz: air.
"""
import cmath, json, math
FS = 48000
CHAIN = [("bq_highpass", 85.0, 0.707, 0), ("bq_highpass", 85.0, 0.707, 0),
         ("bq_peaking", 160.0, 0.9, 4.0), ("bq_peaking", 380.0, 1.4, -2.5),
         ("bq_peaking", 2800.0, 1.2, -1.5), ("bq_highshelf", 9000.0, 0.7, 2.0)]

def coeffs(kind, f, q, g):  # RBJ audio EQ cookbook, as used by PipeWire's builtin biquads
    A = 10 ** (g / 40); w = 2 * math.pi * f / FS; c, s = math.cos(w), math.sin(w); al = s / (2 * q)
    if kind == "bq_highpass":
        b = [(1 + c) / 2, -(1 + c), (1 + c) / 2]; a = [1 + al, -2 * c, 1 - al]
    elif kind == "bq_peaking":
        b = [1 + al * A, -2 * c, 1 - al * A]; a = [1 + al / A, -2 * c, 1 - al / A]
    elif kind == "bq_highshelf":
        sq = 2 * math.sqrt(A) * al
        b = [A * ((A + 1) + (A - 1) * c + sq), -2 * A * ((A - 1) + (A + 1) * c), A * ((A + 1) + (A - 1) * c - sq)]
        a = [(A + 1) - (A - 1) * c + sq, 2 * ((A - 1) - (A + 1) * c), (A + 1) - (A - 1) * c - sq]
    return b, a

def response_db(f):
    z = cmath.exp(-1j * 2 * math.pi * f / FS); h = 1
    for kind, fc, q, g in CHAIN:
        b, a = coeffs(kind, fc, q, g)
        h *= (b[0] + b[1] * z + b[2] * z * z) / (a[0] + a[1] * z + a[2] * z * z)
    return 20 * math.log10(abs(h))

freqs = [20 * (1000 ** (i / 600)) for i in range(601)]  # 20 Hz .. 20 kHz, log-spaced
peak = max(response_db(f) for f in freqs)
pregain_db = -(peak + 0.5)
print(f"peak boost {peak:+.2f} dB  ->  pre-gain {pregain_db:+.2f} dB  (linear {10**(pregain_db/20):.4f})")
for f in (50, 85, 120, 160, 250, 380, 1000, 2800, 6000, 10000, 16000):
    print(f"  {f:>6} Hz  {response_db(f) + pregain_db:+6.2f} dB net")
json.dump({"chain": CHAIN, "pregain_linear": round(10 ** (pregain_db / 20), 4), "pregain_db": round(pregain_db, 2)},
          open("eq_design.json", "w"), indent=1)

# ---- render the Omarchy-format tuning fragment from the same numbers ----
nodes, links, _last = [], [], {}  # _last: final filter of each channel's chain
for ch in ("l", "r"):
    nodes.append(f'          {{ type = builtin name = pre_{ch} label = mixer control = {{ "Gain 1" = {10 ** (pregain_db / 20):.4f} }} }}')
    prev = f"pre_{ch}"
    for i, (kind, f, q, g) in enumerate(CHAIN):
        ctl = f'"Freq" = {f} "Q" = {q}' + (f' "Gain" = {g}' if kind != "bq_highpass" else "")
        nodes.append(f'          {{ type = builtin name = s{i}_{ch} label = {kind} control = {{ {ctl} }} }}')
        links.append(f'          {{ output = "{prev}:Out" input = "s{i}_{ch}:In" }}'); prev = f"s{i}_{ch}"
    _last[ch] = prev
conf = f'''# MacBook Pro 15" Retina (MacBookPro11,3) internal speakers — generated by design_eq.py; edit that, not this.
#
# Unmeasured voicing for small laptop drivers (see design_eq.py for the reasoning behind each filter).
# Installed in Omarchy's speaker-tuning layout so `omarchy audio tuning status|off` manage it and Omarchy's
# volume keys resolve through it to the real speakers. No limiter (lsp-plugins-lv2 is not installed):
# instead the pre-gain ({pregain_db:+.2f} dB) keeps the whole chain at or below -0.5 dB at every frequency,
# so it cannot clip.

context.modules = [
  {{ name = libpipewire-module-filter-chain
    args = {{
      node.description = "MacBook Speakers"
      media.name       = "MacBook Speakers"
      filter.graph = {{
        nodes = [
{chr(10).join(nodes)}
        ]
        links = [
{chr(10).join(links)}
        ]
        inputs  = [ "pre_l:In 1" "pre_r:In 1" ]
        outputs = [ "{_last['l']}:Out" "{_last['r']}:Out" ]
      }}
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {{
        node.name   = "omarchy_speaker_tuning"
        media.class = Audio/Sink
      }}
      playback.props = {{
        node.name     = "omarchy_speaker_tuning_output"
        node.passive  = true
        target.object = "alsa_output.pci-0000_00_1b.0.analog-stereo"
        # Same guards as Omarchy's own tunings: never get dragged to another output, and wait for the
        # speakers rather than silently processing whatever the default device happens to be.
        node.dont-move     = true
        node.dont-fallback = true
        node.linger        = true
      }}
    }}
  }}
]
'''
open("macbookpro11-speakers.conf", "w").write(conf)
print("wrote macbookpro11-speakers.conf")
