# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#d7f2ff"

# Title color for boxes
theme[title]="#a874ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#3fd0e6"

# Background color of selected item in processes box
theme[selected_bg]="#2f1b57"

# Foreground color of selected item in processes box
theme[selected_fg]="#f2fcff"

# Color of inactive/disabled text
theme[inactive_fg]="#8174aa"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c07cff"

# Box outline and divider line color
theme[cpu_box]="#a874ff"
theme[mem_box]="#a874ff"
theme[net_box]="#a874ff"
theme[proc_box]="#a874ff"
theme[div_line]="#2f1b57"

# Gradient for all meters and graphs
theme[temp_start]="#3fd0e6"
theme[temp_mid]="#f5c83d"
theme[temp_end]="#ff5468"

theme[cpu_start]="#7aef3e"
theme[cpu_mid]="#ff9330"
theme[cpu_end]="#ff5468"

theme[free_start]="#7aef3e"
theme[free_mid]="#7aef3e"
theme[free_end]="#b4ff7a"

theme[cached_start]="#3fd0e6"
theme[cached_mid]="#3fd0e6"
theme[cached_end]="#7cecfa"

theme[available_start]="#6b8fff"
theme[available_mid]="#6b8fff"
theme[available_end]="#97b0ff"

theme[used_start]="#f5c83d"
theme[used_mid]="#ff9330"
theme[used_end]="#ff5468"

theme[download_start]="#3fd0e6"
theme[download_mid]="#6b8fff"
theme[download_end]="#d6a3ff"

theme[upload_start]="#c07cff"
theme[upload_mid]="#a874ff"
theme[upload_end]="#d6a3ff"
